"""
Script to create the complete 65 approved reference drugs catalog in DrugBank.
Expands from 50 to 65 drugs for Drug-OPT Global Engine v3.2.
"""
import json
from pathlib import Path

# Load original 50 drugs
with open("/home/xavier/chem/drug-opt-platform/backend/reference_drugs_50.json") as f:
    ORIGINAL_50 = json.load(f)

# Update Drugs 46-50 (Raloxifene, Tamoxifen, Theophylline, Tolbutamide, Trazodone)
# to FINAL_TEST_COHORT_3_CONSUMED because they were evaluated in v3.1 locked final test.
for d in ORIGINAL_50:
    if d["name"] in ("Raloxifene", "Tamoxifen", "Theophylline", "Tolbutamide", "Trazodone"):
        d["model_role"] = "FINAL_TEST_COHORT_3_CONSUMED"
        d["cohort"] = "FINAL_TEST_COHORT_3_CONSUMED"

# Define 15 new approved reference drugs (51-65)
NEW_15_DRUGS = [
    # 51: Fluvoxamine (DEVELOPMENT_TRAINING)
    {
        "name": "Fluvoxamine", "cas_number": "54710-57-1", "drugbank_id": "DB00176", "pubchem_cid": "5324346", "chembl_id": "CHEMBL715", "unii": "444094Y354",
        "smiles": "COCCCC(=NOCCN)c1ccc(C(F)(F)F)cc1", "indication": "Obsessive-Compulsive Disorder / Major Depressive Disorder", "target": "Serotonin Transporter (SERT) / Potent CYP1A2 & CYP2C19 Inhibitor", "scaffold_family": "Phenyloxime-aminoalkylether",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2 / Human Liver Microsomes", "raw_value": 0.041, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 41.0, "normalized_unit": "nM", "reference_text": "FDA Clinical Drug Interaction Guidance Reference / ChEMBL715", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19 / Human Liver Microsomes", "raw_value": 0.10, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 100.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Guidance / ChEMBL715", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9", "raw_value": 4.8, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 4800.0, "normalized_unit": "nM", "reference_text": "ChEMBL715 / DrugBank", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 2.1e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.68, "normalized_unit": "log10(cm/s)", "reference_text": "Yazdanian et al. / DrugBank", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 18.5, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.27, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 80.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 80.0, "normalized_unit": "% bound", "reference_text": "FDA Luvox NDA Clinical Pharmacology Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 3.8, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 3800.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL715", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    # 52: Ticlopidine (DEVELOPMENT_TRAINING)
    {
        "name": "Ticlopidine", "cas_number": "55142-85-3", "drugbank_id": "DB00188", "pubchem_cid": "5472", "chembl_id": "CHEMBL672", "unii": "0F5N58N645",
        "smiles": "Clc1ccccc1CN1CCc2sccc2C1", "indication": "Thromboembolic Stroke Prevention", "target": "Platelet P2Y12 Receptor / Potent CYP2C19 Mechanism-Based Inhibitor", "scaffold_family": "Thienopyridine",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19 / Human Liver Microsomes", "raw_value": 0.20, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 200.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Guidance / ChEMBL672", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 1.2, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 1200.0, "normalized_unit": "nM", "reference_text": "ChEMBL672 / DrugBank", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9", "raw_value": 3.5, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 3500.0, "normalized_unit": "nM", "reference_text": "ChEMBL672", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 1.8e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.74, "normalized_unit": "log10(cm/s)", "reference_text": "Artursson et al. / DrugBank", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 85.0, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.93, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 98.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 98.0, "normalized_unit": "% bound", "reference_text": "FDA Ticlid NDA Clinical Pharmacology Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 1.5, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 1500.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL672", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    # 53: Miconazole (DEVELOPMENT_TRAINING)
    {
        "name": "Miconazole", "cas_number": "22916-47-8", "drugbank_id": "DB01110", "pubchem_cid": "4189", "chembl_id": "CHEMBL95", "unii": "7NNO0D7JW5",
        "smiles": "Clc1ccc(Cl)c(C(Cn2ccnc2)OCc2ccc(Cl)c(Cl)c2)c1", "indication": "Fungal Infections / Candidiasis", "target": "Lanosterol 14-alpha Demethylase / Potent CYP2C9 & CYP3A4 Inhibitor", "scaffold_family": "Imidazole-diarylether",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9 / Human Liver Microsomes", "raw_value": 0.45, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 450.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Guidance / ChEMBL95", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 0.18, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 180.0, "normalized_unit": "nM", "reference_text": "ChEMBL95 / DrugBank", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 0.25, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 250.0, "normalized_unit": "nM", "reference_text": "ChEMBL95", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 1.2e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.92, "normalized_unit": "log10(cm/s)", "reference_text": "ChEMBL95 / DrugBank", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 45.0, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.65, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 98.7, "raw_unit": "%", "raw_relation": "=", "normalized_value": 98.7, "normalized_unit": "% bound", "reference_text": "FDA Monistat NDA Review / DrugBank", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 2.1, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 2100.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL95", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    # 54: Ciprofloxacin (DEVELOPMENT_TRAINING)
    {
        "name": "Ciprofloxacin", "cas_number": "85721-33-1", "drugbank_id": "DB00537", "pubchem_cid": "2764", "chembl_id": "CHEMBL8", "unii": "5E8K9I0O4E",
        "smiles": "O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O", "indication": "Bacterial Infections", "target": "Bacterial DNA Gyrase / Moderate CYP1A2 Inhibitor", "scaffold_family": "Fluoroquinolone-piperazine",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2 / Human Liver Microsomes", "raw_value": 8.5, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 8500.0, "normalized_unit": "nM", "reference_text": "FDA Cipro NDA Clinical Review / ChEMBL8", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9", "raw_value": 120.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 120000.0, "normalized_unit": "nM", "reference_text": "ChEMBL8 / DrugBank", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 150.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 150000.0, "normalized_unit": "nM", "reference_text": "ChEMBL8", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 0.75e-6, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -6.12, "normalized_unit": "log10(cm/s)", "reference_text": "Artursson et al. / DrugBank", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 3.5, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 0.54, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 30.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 30.0, "normalized_unit": "% bound", "reference_text": "FDA Cipro NDA Clinical Pharmacology Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 75.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 75000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL8", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    # 55: Sulfaphenazole (DEVELOPMENT_TRAINING)
    {
        "name": "Sulfaphenazole", "cas_number": "526-08-9", "drugbank_id": "DB01244", "pubchem_cid": "5337", "chembl_id": "CHEMBL435", "unii": "734W50S87S",
        "smiles": "Nc1ccc(S(=O)(=O)Nc2ccn(-c3ccccc3)n2)cc1", "indication": "Sulfonamide Antibiotic / Canonical In Vitro CYP2C9 Reference Inhibitor", "target": "Bacterial Dihydropteroate Synthase / Selective CYP2C9 Reference Inhibitor", "scaffold_family": "Phenylpyrazolyl-sulfonamide",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9 / Human Liver Microsomes", "raw_value": 0.35, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 350.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Guidance Standard Reference / ChEMBL435", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 85.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 85000.0, "normalized_unit": "nM", "reference_text": "ChEMBL435 / Selective Non-inhibitor Control", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 70.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 70000.0, "normalized_unit": "nM", "reference_text": "ChEMBL435", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 1.6e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.80, "normalized_unit": "log10(cm/s)", "reference_text": "DrugBank / ChEMBL435", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 6.0, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 0.78, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 80.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 80.0, "normalized_unit": "% bound", "reference_text": "DrugCentral / DrugBank", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 45.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 45000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL435", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    # 56: Voriconazole (MODEL_SELECTION_VALIDATION)
    {
        "name": "Voriconazole", "cas_number": "137234-62-9", "drugbank_id": "DB00582", "pubchem_cid": "71616", "chembl_id": "CHEMBL779", "unii": "JFU09I87TR",
        "smiles": "CC(C(Cn1cncn1)(O)c2ccc(F)cc2F)c3ncc(F)cn3", "indication": "Invasive Fungal Infections / Aspergillosis", "target": "CYP51 / Extensive Substrate & Moderate CYP2C19 & CYP2C9 Inhibitor", "scaffold_family": "Fluoropyrimidinyl-triazolyl-ethanol",
        "model_role": "MODEL_SELECTION_VALIDATION", "cohort": "VALIDATION_COHORT_2",
        "upstream_overlap": {"CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19 / Human Liver Microsomes", "raw_value": 5.1, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 5100.0, "normalized_unit": "nM", "reference_text": "FDA Vfend NDA Clinical Pharmacology Review / ChEMBL779", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9", "raw_value": 3.8, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 3800.0, "normalized_unit": "nM", "reference_text": "FDA Vfend NDA / ChEMBL779", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 45.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 45000.0, "normalized_unit": "nM", "reference_text": "ChEMBL779", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 1.4e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.85, "normalized_unit": "log10(cm/s)", "reference_text": "DrugBank / ChEMBL779", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 25.0, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.40, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 58.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 58.0, "normalized_unit": "% bound", "reference_text": "FDA Vfend NDA Clinical Pharmacology Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 80.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 80000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL779", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    # 57: Rofecoxib (MODEL_SELECTION_VALIDATION)
    {
        "name": "Rofecoxib", "cas_number": "162011-90-7", "drugbank_id": "DB00533", "pubchem_cid": "5090", "chembl_id": "CHEMBL122", "unii": "0QTW8Z7MCR",
        "smiles": "O=S(=O)(c1ccc(cc1)C2=C(c3ccccc3)C(=O)OC2)C", "indication": "Osteoarthritis / Acute Pain", "target": "COX-2 / Moderate CYP1A2 Inhibitor", "scaffold_family": "Diarylfuranone-methylsulfone",
        "model_role": "MODEL_SELECTION_VALIDATION", "cohort": "VALIDATION_COHORT_2",
        "upstream_overlap": {"CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2 / Human Liver Microsomes", "raw_value": 4.5, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 4500.0, "normalized_unit": "nM", "reference_text": "FDA Vioxx NDA Review / ChEMBL122", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9", "raw_value": 35.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 35000.0, "normalized_unit": "nM", "reference_text": "ChEMBL122", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 50.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 50000.0, "normalized_unit": "nM", "reference_text": "ChEMBL122", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 2.2e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.66, "normalized_unit": "log10(cm/s)", "reference_text": "DrugBank / ChEMBL122", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 12.0, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.08, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 87.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 87.0, "normalized_unit": "% bound", "reference_text": "FDA Vioxx NDA Clinical Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 60.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 60000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL122", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    # 58: Fenofibrate (MODEL_SELECTION_VALIDATION)
    {
        "name": "Fenofibrate", "cas_number": "49562-28-9", "drugbank_id": "DB01039", "pubchem_cid": "3339", "chembl_id": "CHEMBL533", "unii": "U202363NEQ",
        "smiles": "CC(C)OC(=O)C(C)(C)Oc1ccc(C(=O)c2ccc(Cl)cc2)cc1", "indication": "Hypercholesterolemia / Mixed Dyslipidemia", "target": "PPAR-alpha / Moderate CYP2C9 & CYP2A6 Inhibitor", "scaffold_family": "Benzophenone-phenoxyisobutyrate",
        "model_role": "MODEL_SELECTION_VALIDATION", "cohort": "VALIDATION_COHORT_2",
        "upstream_overlap": {"CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9 / Human Liver Microsomes", "raw_value": 2.8, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 2800.0, "normalized_unit": "nM", "reference_text": "ChEMBL533 / FDA Tricor Review", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 25.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "ChEMBL533", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 15.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 15000.0, "normalized_unit": "nM", "reference_text": "ChEMBL533", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 1.9e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.72, "normalized_unit": "log10(cm/s)", "reference_text": "DrugBank / ChEMBL533", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 95.0, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.98, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 99.0, "normalized_unit": "% bound", "reference_text": "FDA Tricor NDA Clinical Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 30.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL533", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    # 59: Glimepiride (MODEL_SELECTION_VALIDATION)
    {
        "name": "Glimepiride", "cas_number": "93479-97-1", "drugbank_id": "DB00222", "pubchem_cid": "3476", "chembl_id": "CHEMBL459", "unii": "6KY687524C",
        "smiles": "CCC1=C(C)C(=O)N(CCN1C(=O)N)c2ccc(S(=O)(=O)NC(=O)NC3CCC(C)CC3)cc2", "indication": "Type 2 Diabetes Mellitus", "target": "Sulfonylurea Receptor 1 (SUR1) / Primary CYP2C9 Substrate", "scaffold_family": "Sulfonylurea-pyrrolinone",
        "model_role": "MODEL_SELECTION_VALIDATION", "cohort": "VALIDATION_COHORT_2",
        "upstream_overlap": {"CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9 / Human Liver Microsomes", "raw_value": 3.2, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 3200.0, "normalized_unit": "nM", "reference_text": "FDA Amaryl NDA Clinical Pharmacology Review / ChEMBL459", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 80.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 80000.0, "normalized_unit": "nM", "reference_text": "ChEMBL459", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 45.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 45000.0, "normalized_unit": "nM", "reference_text": "ChEMBL459", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 1.1e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.96, "normalized_unit": "log10(cm/s)", "reference_text": "DrugBank / ChEMBL459", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 14.0, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.15, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.5, "raw_unit": "%", "raw_relation": "=", "normalized_value": 99.5, "normalized_unit": "% bound", "reference_text": "FDA Amaryl NDA Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 55.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 55000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL459", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    # 60: Zafirlukast (MODEL_SELECTION_VALIDATION)
    {
        "name": "Zafirlukast", "cas_number": "107753-78-6", "drugbank_id": "DB00549", "pubchem_cid": "5702143", "chembl_id": "CHEMBL644", "unii": "XZ629S5L50",
        "smiles": "COc1cc(cc(c1)S(=O)(=O)NC(=O)c2c(C)n(c3ccccc23)C)Cc4cccc(c4)NC(=O)OC5CCCC5", "indication": "Asthma Prophylaxis & Chronic Treatment", "target": "Cysteinyl Leukotriene Receptor 1 (CysLT1) / Potent CYP2C9 Inhibitor", "scaffold_family": "Indole-sulfonamidocarbamate",
        "model_role": "MODEL_SELECTION_VALIDATION", "cohort": "VALIDATION_COHORT_2",
        "upstream_overlap": {"CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9 / Human Liver Microsomes", "raw_value": 0.28, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 280.0, "normalized_unit": "nM", "reference_text": "FDA Accolate NDA Clinical Review / ChEMBL644", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 4.2, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 4200.0, "normalized_unit": "nM", "reference_text": "ChEMBL644", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 2.1, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 2100.0, "normalized_unit": "nM", "reference_text": "ChEMBL644", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 0.85e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -5.07, "normalized_unit": "log10(cm/s)", "reference_text": "DrugBank / ChEMBL644", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 20.0, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.30, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 99.0, "normalized_unit": "% bound", "reference_text": "FDA Accolate NDA Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 1.2, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 1200.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL644", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    # 61: Probenecid (LOCKED_FINAL_TEST_COHORT_4)
    {
        "name": "Probenecid", "cas_number": "57-66-9", "drugbank_id": "DB01032", "pubchem_cid": "4911", "chembl_id": "CHEMBL447", "unii": "P0404A532F",
        "smiles": "CCCN(CCC)S(=O)(=O)c1ccc(C(=O)O)cc1", "indication": "Hyperuricemia / Gout", "target": "OAT1 / OAT3 / MRP4 Renal Transporter Inhibitor", "scaffold_family": "Dipropylsulfamoylbenzoic-acid",
        "model_role": "LOCKED_FINAL_TEST_COHORT_4", "cohort": "LOCKED_FINAL_TEST_COHORT_4",
        "upstream_overlap": {"CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN"},
        "observations": [
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 1.7e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.77, "normalized_unit": "log10(cm/s)", "reference_text": "DrugBank / ChEMBL447", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 4.8, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 0.68, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 120.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 120000.0, "normalized_unit": "nM", "reference_text": "ChEMBL447", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9", "raw_value": 50.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 50000.0, "normalized_unit": "nM", "reference_text": "ChEMBL447", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 80.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 80000.0, "normalized_unit": "nM", "reference_text": "ChEMBL447", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 88.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 88.0, "normalized_unit": "% bound", "reference_text": "FDA Benemid NDA Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 150.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 150000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL447", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 150.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 150000.0, "normalized_unit": "nM", "reference_text": "ChEMBL447", "assay_type": "Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 180.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 180000.0, "normalized_unit": "nM", "reference_text": "ChEMBL447", "assay_type": "Dextromethorphan O-demethylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 120.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -3.92, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Benemid NDA", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True}
        ]
    },
    # 62: Carbamazepine (LOCKED_FINAL_TEST_COHORT_4)
    {
        "name": "Carbamazepine", "cas_number": "298-46-4", "drugbank_id": "DB00564", "pubchem_cid": "2554", "chembl_id": "CHEMBL107", "unii": "33CM04F73V",
        "smiles": "NC(=O)N1c2ccccc2C=Cc3ccccc13", "indication": "Epilepsy / Trigeminal Neuralgia", "target": "Voltage-Gated Sodium Channels / CYP3A4 Substrate & Inducer", "scaffold_family": "Dibenzazepine-carboxamide",
        "model_role": "LOCKED_FINAL_TEST_COHORT_4", "cohort": "LOCKED_FINAL_TEST_COHORT_4",
        "upstream_overlap": {"CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN"},
        "observations": [
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 3.4e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.47, "normalized_unit": "log10(cm/s)", "reference_text": "Artursson et al. / Yazdanian et al.", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 16.0, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.20, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 95.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 95000.0, "normalized_unit": "nM", "reference_text": "ChEMBL107", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9", "raw_value": 75.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 75000.0, "normalized_unit": "nM", "reference_text": "ChEMBL107", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 60.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 60000.0, "normalized_unit": "nM", "reference_text": "ChEMBL107", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 76.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 76.0, "normalized_unit": "% bound", "reference_text": "FDA Tegretol NDA Clinical Pharmacology Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 42.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 42000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL107", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 85.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 85000.0, "normalized_unit": "nM", "reference_text": "FDA Tegretol NDA Review / ChEMBL107", "assay_type": "Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 120.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 120000.0, "normalized_unit": "nM", "reference_text": "FDA Tegretol Review", "assay_type": "Dextromethorphan O-demethylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 75.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.12, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Tegretol NDA", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True}
        ]
    },
    # 63: Clotrimazole (LOCKED_FINAL_TEST_COHORT_4)
    {
        "name": "Clotrimazole", "cas_number": "23593-75-1", "drugbank_id": "DB00257", "pubchem_cid": "2812", "chembl_id": "CHEMBL112", "unii": "G07GZ97H65",
        "smiles": "Clc1ccccc1C(c2ccccc2)(c3ccccc3)n4ccnc4", "indication": "Fungal Infections / Candidiasis", "target": "CYP51 / Broad Potent CYP Inhibitor", "scaffold_family": "Chlorophenyl-tritylimidazole",
        "model_role": "LOCKED_FINAL_TEST_COHORT_4", "cohort": "LOCKED_FINAL_TEST_COHORT_4",
        "upstream_overlap": {"CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN"},
        "observations": [
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2 / Human Liver Microsomes", "raw_value": 0.15, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 150.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Guidance / ChEMBL112", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9", "raw_value": 0.25, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 250.0, "normalized_unit": "nM", "reference_text": "ChEMBL112", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 0.30, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 300.0, "normalized_unit": "nM", "reference_text": "ChEMBL112", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 1.5e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.82, "normalized_unit": "log10(cm/s)", "reference_text": "DrugBank / ChEMBL112", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 60.0, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.78, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 98.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 98.0, "normalized_unit": "% bound", "reference_text": "FDA Lotrimin NDA Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 2.8, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 2800.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL112", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 0.05, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 50.0, "normalized_unit": "nM", "reference_text": "FDA Metabolism Guidance / ChEMBL112", "assay_type": "Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 15.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 15000.0, "normalized_unit": "nM", "reference_text": "ChEMBL112", "assay_type": "Dextromethorphan O-demethylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 1.5, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -5.82, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Lotrimin NDA", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True}
        ]
    },
    # 64: Ranitidine (LOCKED_FINAL_TEST_COHORT_4)
    {
        "name": "Ranitidine", "cas_number": "66357-35-5", "drugbank_id": "DB00863", "pubchem_cid": "5039", "chembl_id": "CHEMBL64", "unii": "884KT10YB3",
        "smiles": "CN/C(=C\\[N+](=O)[O-])/NCCSCc1ccc(CN(C)C)o1", "indication": "Peptic Ulcer / GERD", "target": "Histamine H2 Receptor / Weak CYP Inhibitor", "scaffold_family": "Dimethylaminomethyl-furanyl-nitroethenediamine",
        "model_role": "LOCKED_FINAL_TEST_COHORT_4", "cohort": "LOCKED_FINAL_TEST_COHORT_4",
        "upstream_overlap": {"CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN"},
        "observations": [
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 1.2e-6, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -5.92, "normalized_unit": "log10(cm/s)", "reference_text": "Artursson et al. / FDA Review", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 5.5, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 0.74, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 150.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 150000.0, "normalized_unit": "nM", "reference_text": "ChEMBL64", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9", "raw_value": 180.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 180000.0, "normalized_unit": "nM", "reference_text": "ChEMBL64", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 160.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 160000.0, "normalized_unit": "nM", "reference_text": "ChEMBL64", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 15.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 15.0, "normalized_unit": "% bound", "reference_text": "FDA Zantac NDA Clinical Pharmacology Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 220.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 220000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL64", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 200.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 200000.0, "normalized_unit": "nM", "reference_text": "FDA Zantac Review / ChEMBL64", "assay_type": "Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 250.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 250000.0, "normalized_unit": "nM", "reference_text": "ChEMBL64", "assay_type": "Dextromethorphan O-demethylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 6500.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -2.19, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Zantac NDA", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True}
        ]
    },
    # 65: Phenytoin (LOCKED_FINAL_TEST_COHORT_4)
    {
        "name": "Phenytoin", "cas_number": "57-41-0", "drugbank_id": "DB00252", "pubchem_cid": "1775", "chembl_id": "CHEMBL16", "unii": "6158TKW0C5",
        "smiles": "O=C1NC(=O)C(c2ccccc2)(c3ccccc3)N1", "indication": "Tonic-Clonic & Focal Seizures", "target": "Voltage-Gated Sodium Channels / Prototype CYP2C9 Substrate", "scaffold_family": "Diphenylhydantoin",
        "model_role": "LOCKED_FINAL_TEST_COHORT_4", "cohort": "LOCKED_FINAL_TEST_COHORT_4",
        "upstream_overlap": {"CYP2C9_INHIBITION": "NOVEL_IN_DOMAIN", "CYP1A2_INHIBITION": "NOVEL_IN_DOMAIN", "CYP2C19_INHIBITION": "NOVEL_IN_DOMAIN", "CACO2_PERMEABILITY": "NOVEL_IN_DOMAIN", "HLM_INTRINSIC_CLEARANCE": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "HERG_LIABILITY": "VALIDATION_HOLDOUT", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN"},
        "observations": [
            {"canonical_endpoint_id": "CYP2C9_INHIBITION", "raw_endpoint_name": "CYP2C9 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C9 / Human Liver Microsomes", "raw_value": 6.5, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 6500.0, "normalized_unit": "nM", "reference_text": "FDA Dilantin NDA Review / ChEMBL16", "assay_type": "Diclofenac 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP1A2", "raw_value": 80.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 80000.0, "normalized_unit": "nM", "reference_text": "ChEMBL16", "assay_type": "Phenacetin O-deethylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2C19_INHIBITION", "raw_endpoint_name": "CYP2C19 Direct Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2C19", "raw_value": 25.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "ChEMBL16", "assay_type": "S-Mephenytoin 4'-hydroxylation LC-MS/MS", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PERMEABILITY", "raw_endpoint_name": "Caco-2 Apparent Permeability", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer pH 7.4/7.4", "raw_value": 2.3e-5, "raw_unit": "cm/s", "raw_relation": "=", "normalized_value": -4.64, "normalized_unit": "log10(cm/s)", "reference_text": "Artursson et al. / Yazdanian et al.", "assay_type": "Bidirectional Caco-2 Cell Permeability (A to B)", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_INTRINSIC_CLEARANCE", "raw_endpoint_name": "Human Liver Microsomes Intrinsic Clearance", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Human Liver Microsomes (HLM)", "raw_value": 12.5, "raw_unit": "µL/min/mg", "raw_relation": "=", "normalized_value": 1.10, "normalized_unit": "log10(mL/min/kg)", "reference_text": "Obach et al. 1999 J Pharmacol Exp Ther", "assay_type": "Substrate Depletion (HLM + NADPH)", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 90.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 90.0, "normalized_unit": "% bound", "reference_text": "FDA Dilantin NDA Review", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 48.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 48000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL16", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 100.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 100000.0, "normalized_unit": "nM", "reference_text": "FDA Dilantin Review / ChEMBL16", "assay_type": "Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 150.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 150000.0, "normalized_unit": "nM", "reference_text": "ChEMBL16", "assay_type": "Dextromethorphan O-demethylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 70.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.15, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Dilantin NDA", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True}
        ]
    }
]

ALL_65_DRUGS = ORIGINAL_50 + NEW_15_DRUGS
out_path = Path("/home/xavier/chem/drug-opt-platform/backend/reference_drugs_65.json")
with open(out_path, "w") as f:
    json.dump(ALL_65_DRUGS, f, indent=2)

print(f"Successfully generated {out_path} with {len(ALL_65_DRUGS)} approved reference drugs.")
