"""
Generator script to build the full 40 approved reference drugs catalog in DrugBank.
"""
import json
from pathlib import Path

# Load original 20 drugs from existing drugbank_reference
from backend.drugbank_reference import REFERENCE_DRUGS_CATALOG as ORIGINAL_20

# Update Cimetidine role to FINAL_TEST_COHORT_1_CONSUMED
for d in ORIGINAL_20:
    if d["name"] == "Cimetidine":
        d["model_role"] = "FINAL_TEST_COHORT_1_CONSUMED"
        d["cohort"] = "FINAL_TEST_COHORT_1_CONSUMED"

# Add 20 new drugs (21 to 40)
NEW_20_DRUGS = [
    # 21-30: DEVELOPMENT_TRAINING
    {
        "name": "Bupropion", "cas_number": "34897-89-9", "drugbank_id": "DB01156", "pubchem_cid": "444", "chembl_id": "CHEMBL896", "unii": "01ZG3R2U1J",
        "smiles": "CC(C)(C)NC(C)C(=O)c1cccc(Cl)c1", "indication": "Depression / Smoking Cessation", "target": "NET / DAT / Potent CYP2D6 Inhibitor", "scaffold_family": "Aminoketone",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 0.06, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 60.0, "normalized_unit": "nM", "reference_text": "FDA Drug Interaction Review / Wellbutrin NDA 018644", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 33.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 33000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 84.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 84.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Wellbutrin Label NDA 018644", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 2000.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -2.70, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Wellbutrin NDA 018644", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 22.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 22000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL896", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Carvedilol", "cas_number": "72956-09-3", "drugbank_id": "DB01136", "pubchem_cid": "2585", "chembl_id": "CHEMBL800", "unii": "0K45R74LQW",
        "smiles": "COc1ccccc1OCCNCC(O)COc1cccc2[nH]c3ccccc3c12", "indication": "Heart Failure / Hypertension", "target": "Beta-1/Beta-2/Alpha-1 Adrenergic Receptors", "scaffold_family": "Carbazole-aryloxypropanolamine",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 2.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 2000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Coreg NDA 020297", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 12.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 12000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 98.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 98.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Coreg Label NDA 020297", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 2.2, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -5.66, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Coreg NDA 020297", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 0.35, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 350.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL800", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Clopidogrel", "cas_number": "113665-84-2", "drugbank_id": "DB00758", "pubchem_cid": "60606", "chembl_id": "CHEMBL1771", "unii": "A74586SNO7",
        "smiles": "COC(=O)C(c1ccccc1Cl)N1CCc2sccc2C1", "indication": "Atherothrombosis / Acute Coronary Syndrome", "target": "P2Y12 Receptor / CYP2C19 & CYP3A4 Substrate", "scaffold_family": "Thienopyridine",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 30.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Plavix NDA 020839", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 9.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 9000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Plavix", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 98.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 98.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Plavix Label NDA 020839", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 14.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.85, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Plavix NDA 020839", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 8.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 8000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL1771", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Diltiazem", "cas_number": "42399-41-7", "drugbank_id": "DB00343", "pubchem_cid": "39186", "chembl_id": "CHEMBL436", "unii": "EE92BBP03H",
        "smiles": "CC(=O)OC1C(=O)N(CCN(C)C)c2ccccc2Sc2ccc(OC)cc21", "indication": "Angina / Hypertension / Arrhythmia", "target": "Cav1.2 Calcium Channel / Moderate CYP3A4 Inhibitor", "scaffold_family": "Benzothiazepine",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 40.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 40000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Cardizem NDA 018602", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 4.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 4000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Drug Interaction Guidance Moderate Inhibitor", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 78.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 78.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Cardizem Label NDA 018602", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 350.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -3.45, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Cardizem NDA 018602", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 9.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 9000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL436", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Erythromycin", "cas_number": "114-07-8", "drugbank_id": "DB00199", "pubchem_cid": "12560", "chembl_id": "CHEMBL544", "unii": "63937KV33D",
        "smiles": "CCC1OC(=O)C(C)C(OC2CC(C)(OC)C(O)C(C)O2)C(C)C(OC2OC(C)CC(N(C)C)C2O)C(C)(O)CC(C)C(=O)C(C)C(O)C1(C)O", "indication": "Bacterial Infections / Moderate CYP3A4 Inhibitor", "target": "50S Ribosomal Subunit / CYP3A4 Substrate/Inhibitor", "scaffold_family": "Macrolide",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 100.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 100000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Erythrocin NDA 050120", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 2.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 2000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Drug Interaction Guidance Moderate Inhibitor", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 84.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 84.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Erythrocin Label NDA 050120", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 25.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.60, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Erythrocin NDA 050120", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 6.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 6000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL544", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Flecainide", "cas_number": "54143-55-4", "drugbank_id": "DB01129", "pubchem_cid": "3356", "chembl_id": "CHEMBL798", "unii": "K92381WP3H",
        "smiles": "O=C(NCC1CCCCN1)c1cc(OCC(F)(F)F)ccc1OCC(F)(F)F", "indication": "Arrhythmias / Tachycardia", "target": "Nav1.5 Channel / Potent CYP2D6 Substrate & Inhibitor", "scaffold_family": "Benzamide-piperidine",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 1.5, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 1500.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Tambocor NDA 019032", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 60.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 60000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Tambocor", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 40.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 40.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Tambocor Label NDA 019032", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 250.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -3.60, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Tambocor NDA 019032", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 0.40, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 400.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL798", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Lansoprazole", "cas_number": "103577-45-3", "drugbank_id": "DB00483", "pubchem_cid": "3883", "chembl_id": "CHEMBL481", "unii": "0K5C5T2Q81",
        "smiles": "Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccccc2[nH]1", "indication": "GERD / Peptic Ulcer Disease", "target": "H+/K+ ATPase / CYP2C19 & CYP3A4 Inhibitor", "scaffold_family": "Benzimidazole-sulfinyl",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 25.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Prevacid NDA 020406", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 3.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 3000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Prevacid", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 97.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 97.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Prevacid Label NDA 020406", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 42.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.38, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Prevacid NDA 020406", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 14.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 14000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL481", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Nifedipine", "cas_number": "21829-25-4", "drugbank_id": "DB01115", "pubchem_cid": "4485", "chembl_id": "CHEMBL183", "unii": "I9ZF7L6G2L",
        "smiles": "COC(=O)C1=C(C)NC(C)=C(C(=O)OC)C1c1ccccc1[N+](=O)[O-]", "indication": "Hypertension / Angina", "target": "Cav1.2 Calcium Channel / Standard CYP3A4 Substrate", "scaffold_family": "Dihydropyridine",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 63.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 63000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Procardia NDA 018615", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 5.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 5000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Guidance Standard Substrate", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 95.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 95.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Procardia Label NDA 018615", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 23.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.64, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Procardia NDA 018615", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 25.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL183", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Omeprazole", "cas_number": "73590-58-6", "drugbank_id": "DB00338", "pubchem_cid": "4594", "chembl_id": "CHEMBL1503", "unii": "KG60484QX9",
        "smiles": "COc1ccc2[nH]c(S(=O)Cc3ncc(C)c(OC)c3C)nc2c1", "indication": "Peptic Ulcer / GERD", "target": "H+/K+ ATPase / CYP2C19 & CYP3A4 Substrate & Inhibitor", "scaffold_family": "Benzimidazole-sulfinyl",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 20.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 20000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Prilosec NDA 019810", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 4.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 4000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Prilosec", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 95.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 95.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Prilosec Label NDA 019810", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 100.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.00, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Prilosec NDA 019810", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 19.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 19000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL1503", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Simvastatin", "cas_number": "79902-63-9", "drugbank_id": "DB00641", "pubchem_cid": "54454", "chembl_id": "CHEMBL1481", "unii": "AGG2FN16EV",
        "smiles": "CCC(C)(C)C(=O)OC1CC(C)C=C2C=CC(C)C(CCC3CC(O)CC(=O)O3)C21", "indication": "Hypercholesterolemia / Dyslipidemia", "target": "HMG-CoA Reductase / High PPB & Standard CYP3A4 Substrate", "scaffold_family": "Hexahydronaphthalene-lactone",
        "model_role": "DEVELOPMENT_TRAINING", "cohort": "DEV_TRAINING",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 80.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 80000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Zocor NDA 019766", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 2.5, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 2500.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Drug Interaction Guidance Standard Substrate", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 98.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 98.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Zocor Label NDA 019766", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 1.8, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -5.74, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Zocor NDA 019766", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 7.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 7000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL1481", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },

    # 31-35: MODEL_SELECTION_VALIDATION (Validation Cohort 2)
    {
        "name": "Celecoxib", "cas_number": "169590-42-5", "drugbank_id": "DB00482", "pubchem_cid": "2662", "chembl_id": "CHEMBL118", "unii": "JCX84Q7J1L",
        "smiles": "Cc1ccc(-c2cc(C(F)(F)F)nn2-c2ccc(S(N)(=O)=O)cc2)cc1", "indication": "Osteoarthritis / Rheumatoid Arthritis", "target": "COX-2 / CYP2C9 & CYP2D6 Inhibitor", "scaffold_family": "Pyrazole-benzenesulfonamide",
        "model_role": "MODEL_SELECTION_VALIDATION", "cohort": "VALIDATION_COHORT_2",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 4.5, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 4500.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Celebrex NDA 020998", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 20.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 20000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Celebrex", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 97.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 97.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Celebrex Label NDA 020998", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 7.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -5.15, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Celebrex NDA 020998", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 12.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 12000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL118", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Diazepam", "cas_number": "439-14-5", "drugbank_id": "DB00829", "pubchem_cid": "3016", "chembl_id": "CHEMBL12", "unii": "Q3JTX2Q7TU",
        "smiles": "CN1C(=O)CN=C(c2ccccc2)c2cc(Cl)ccc21", "indication": "Anxiety / Muscle Spasms / Seizures", "target": "GABA-A Receptor / CYP2C19 & CYP3A4 Substrate", "scaffold_family": "1,4-Benzodiazepine",
        "model_role": "MODEL_SELECTION_VALIDATION", "cohort": "VALIDATION_COHORT_2",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 50.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 50000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Valium NDA 013263", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 7.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 7000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Valium", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 98.5, "raw_unit": "%", "raw_relation": "=", "normalized_value": 98.5, "normalized_unit": "% bound", "reference_text": "DailyMed / Valium Label NDA 013263", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 300.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -3.52, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Valium NDA 013263", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 15.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 15000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL12", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Diclofenac", "cas_number": "15307-86-5", "drugbank_id": "DB00586", "pubchem_cid": "3033", "chembl_id": "CHEMBL139", "unii": "144O8QL0L1",
        "smiles": "O=C(O)Cc1ccccc1Nc1c(Cl)cccc1Cl", "indication": "Pain / Inflammation / Osteoarthritis", "target": "COX-1 / COX-2 / Standard CYP2C9 Probe", "scaffold_family": "Phenylacetic acid",
        "model_role": "MODEL_SELECTION_VALIDATION", "cohort": "VALIDATION_COHORT_2",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 70.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 70000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Voltaren NDA 019201", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 25.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Voltaren", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.5, "raw_unit": "%", "raw_relation": "=", "normalized_value": 99.5, "normalized_unit": "% bound", "reference_text": "DailyMed / Voltaren Label NDA 019201", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 35.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.46, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Voltaren NDA 019201", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 18.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 18000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL139", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Indomethacin", "cas_number": "53-86-1", "drugbank_id": "DB00328", "pubchem_cid": "3715", "chembl_id": "CHEMBL6", "unii": "XXE1CET956",
        "smiles": "COc1ccc2c(c1)c(CC(=O)O)c(C)n2C(=O)c1ccc(Cl)cc1", "indication": "Ankylosing Spondylitis / Gout / Osteoarthritis", "target": "COX-1 / COX-2 / CYP2C9 Substrate", "scaffold_family": "Indole-3-acetic acid",
        "model_role": "MODEL_SELECTION_VALIDATION", "cohort": "VALIDATION_COHORT_2",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 60.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 60000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Indocin NDA 016059", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 30.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Indocin", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 99.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Indocin Label NDA 016059", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 14.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.85, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Indocin NDA 016059", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 35.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 35000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL6", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Warfarin", "cas_number": "81-81-2", "drugbank_id": "DB00682", "pubchem_cid": "54678486", "chembl_id": "CHEMBL1464", "unii": "5Q7ZVV76EI",
        "smiles": "CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O", "indication": "Thromboembolism Prophylaxis / Anticoagulation", "target": "VKORC1 / Narrow Therapeutic Index CYP2C9 & CYP3A4 Substrate", "scaffold_family": "4-Hydroxycoumarin",
        "model_role": "MODEL_SELECTION_VALIDATION", "cohort": "VALIDATION_COHORT_2",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 50.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 50000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Coumadin NDA 009218", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 18.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 18000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Coumadin", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 99.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Coumadin Label NDA 009218", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 32.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.49, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Coumadin NDA 009218", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 25.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL1464", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },

    # 36-40: LOCKED_FINAL_TEST_COHORT_2 (Pristine Locked Final Test)
    {
        "name": "Atenolol", "cas_number": "29122-68-7", "drugbank_id": "DB00335", "pubchem_cid": "2249", "chembl_id": "CHEMBL24", "unii": "50VV3VW0TI",
        "smiles": "CC(C)NCC(O)COc1ccc(CC(N)=O)cc1", "indication": "Hypertension / Angina / Post-MI", "target": "Beta-1 Adrenergic Receptor / Hydrophilic Low-Permeability Reference", "scaffold_family": "Phenoxypropanolamine-acetamide",
        "model_role": "LOCKED_FINAL_TEST_COHORT_2", "cohort": "LOCKED_FINAL_TEST_COHORT_2",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 80.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 80000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Tenormin NDA 018240", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 100.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 100000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Tenormin", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 10.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 10.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Tenormin Label NDA 018240", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 42000.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -1.38, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Tenormin NDA 018240", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 80.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 80000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL24", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Caffeine", "cas_number": "58-08-2", "drugbank_id": "DB00201", "pubchem_cid": "2519", "chembl_id": "CHEMBL113", "unii": "3G6A5W338E",
        "smiles": "Cn1c(=O)c2c(ncn2C)n(C)c1=O", "indication": "CNS Stimulation / Apnea of Prematurity", "target": "Adenosine A1/A2A / FDA Standard CYP1A2 Probe", "scaffold_family": "Methylxanthine",
        "model_role": "LOCKED_FINAL_TEST_COHORT_2", "cohort": "LOCKED_FINAL_TEST_COHORT_2",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 200.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 200000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Cafcit NDA 020793", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 80.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 80000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Cafcit", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 35.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 35.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Cafcit Label NDA 020793", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 100000.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -1.00, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Cafcit NDA 020793", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 400.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 400000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL113", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Ibuprofen", "cas_number": "15687-27-1", "drugbank_id": "DB01050", "pubchem_cid": "3672", "chembl_id": "CHEMBL521", "unii": "WK2XYI10QM",
        "smiles": "CC(C)Cc1ccc(C(C)C(=O)O)cc1", "indication": "Pain / Fever / Dysmenorrhea / Inflammation", "target": "COX-1 / COX-2 / CYP2C9 Substrate", "scaffold_family": "Isobutylphenylpropionic acid",
        "model_role": "LOCKED_FINAL_TEST_COHORT_2", "cohort": "LOCKED_FINAL_TEST_COHORT_2",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 90.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 90000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Motrin NDA 017463", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 40.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 40000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Motrin", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 99.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Motrin Label NDA 017463", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 200.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -3.70, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Motrin NDA 017463", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 30.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL521", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Lorcaserin", "cas_number": "616202-92-7", "drugbank_id": "DB08907", "pubchem_cid": "11658860", "chembl_id": "CHEMBL2103837", "unii": "637E49PO0N",
        "smiles": "CC1CNc2ccc(Cl)cc2C1", "indication": "Chronic Weight Management / Obesity", "target": "5-HT2C Receptor / Moderate CYP2D6 Inhibitor", "scaffold_family": "Benzazepine",
        "model_role": "LOCKED_FINAL_TEST_COHORT_2", "cohort": "LOCKED_FINAL_TEST_COHORT_2",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 2.5, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 2500.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Belviq NDA 022529", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 40.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 40000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Belviq", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 70.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 70.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Belviq Label NDA 022529", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 600.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -3.22, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Belviq NDA 022529", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 4.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 4000.0, "normalized_unit": "nM", "reference_text": "ChEMBL2103837 Safety Pharmacology Review", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
    {
        "name": "Rosuvastatin", "cas_number": "287714-41-4", "drugbank_id": "DB01098", "pubchem_cid": "446157", "chembl_id": "CHEMBL1496", "unii": "413AK5O1OT",
        "smiles": "CC(C)c1nc(N(C)S(=O)(=O)C)nc(-c2ccc(F)cc2)c1C=CC(O)CC(O)CC(=O)O", "indication": "Hypercholesterolemia / Atherosclerosis", "target": "HMG-CoA Reductase / Hydrophilic Statin & OATP1B1 Substrate", "scaffold_family": "Pyrimidine-sulfonamide-heptenoate",
        "model_role": "LOCKED_FINAL_TEST_COHORT_2", "cohort": "LOCKED_FINAL_TEST_COHORT_2",
        "upstream_overlap": {"SOLUBILITY_GENERIC": "NOVEL_IN_DOMAIN", "SOLUBILITY_THERMODYNAMIC": "NOVEL_IN_DOMAIN", "HUMAN_PPB": "NOVEL_IN_DOMAIN", "CYP3A4_INHIBITION": "VALIDATION_HOLDOUT", "CYP2D6_INHIBITION": "VALIDATION_HOLDOUT", "HERG_LIABILITY": "VALIDATION_HOLDOUT"},
        "observations": [
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP2D6", "raw_value": 70.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 70000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review / Crestor NDA 021366", "assay_type": "Recombinant human CYP2D6 Dextromethorphan assay", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "rhCYP3A4", "raw_value": 30.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA In Vitro Metabolism Review Crestor", "assay_type": "Recombinant human CYP3A4 Midazolam 1'-hydroxylation assay", "training_eligible": True},
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 88.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 88.0, "normalized_unit": "% bound", "reference_text": "DailyMed / Crestor Label NDA 021366", "assay_type": "Equilibrium Dialysis (Human Plasma)", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 100.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": -4.00, "normalized_unit": "log10(mol/L)", "reference_text": "DrugCentral / Crestor NDA 021366", "assay_type": "Shake-Flask Thermodynamic Solubility (HPLC/UV)", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 Whole-Cell Patch-Clamp", "raw_value": 50.0, "raw_unit": "µM", "raw_relation": "=", "normalized_value": 50000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. / ChEMBL1496", "assay_type": "Whole-cell Voltage Patch-Clamp Electrophysiology", "training_eligible": True}
        ]
    },
]

ALL_40_DRUGS = ORIGINAL_20 + NEW_20_DRUGS
print(f"Total Combined Drugs: {len(ALL_40_DRUGS)}")

# Save to json file for reference
with open("/home/xavier/chem/drug-opt-platform/backend/reference_drugs_40.json", "w") as f:
    json.dump(ALL_40_DRUGS, f, indent=2)
print("Saved reference_drugs_40.json successfully")
