"""Canonical execution boundary for the 59-endpoint Predict All campaign."""

from __future__ import annotations


CONTRACT_ID = "DrugOPTPredictAllCore/3.3.3-stable-core-v1.2"

PUBLISHABLE_CURRENT_ENDPOINTS = frozenset({
    "MW", "CLOGP", "TPSA", "HBD", "HBA", "ROTB", "FSP3", "QED",
    "FORMAL_CHARGE", "HEAVY_ATOM_COUNT", "SOLUBILITY_GENERIC",
    "CACO2_PAPP_AB", "HUMAN_PPB", "HLM_CLINT", "RLM_CLINT", "MLM_CLINT",
    "CYP1A2_INHIBITION", "CYP1A2_INHIBITOR_CLASS",
    "CYP2C9_INHIBITION", "CYP2C9_INHIBITOR_CLASS",
    "CYP2C19_INHIBITOR_CLASS", "CYP2D6_INHIBITION",
    "CYP2D6_INHIBITOR_CLASS", "CYP3A4_INHIBITION",
    "CYP3A4_INHIBITOR_CLASS", "CYP2C9_SUBSTRATE", "CYP2D6_SUBSTRATE",
    "CYP3A4_SUBSTRATE", "PGP_INHIBITION", "HERG_LIABILITY", "HERG_CLASS",
    "DILI_LIABILITY",
})

MECHANISTIC_EXECUTION_ENDPOINTS = frozenset({
    "PKA", "LOGD_7_4", "METABOLIC_SOFT_SPOTS", "METABOLITE_HYPOTHESES",
})

MODEL_NOT_REGISTERED_ENDPOINTS = frozenset({"HIA", "BBB_PENETRATION"})

MODEL_UNAVAILABLE_ENDPOINTS = frozenset({
    "CYP2C19_INHIBITION", "PGP_INHIBITION_QUANT", "BCRP_INHIBITOR_QUANT",
    "BCRP_INHIBITOR", "OATP1B1_INHIBITOR", "OATP1B3_INHIBITOR",
    "OCT1_INHIBITOR", "OCT2_INHIBITOR", "AMES_MUTAGENICITY",
})

CURRENT_DATA_CEILING_ENDPOINTS = frozenset({
    "HUMAN_FU_PLASMA", "VDSS", "HUMAN_HEPATIC_CL", "HUMAN_TOTAL_IV_CL",
    "IV_HALF_LIFE",
})

CONTEXT_REQUIRED_ENDPOINTS = frozenset({
    "HUMAN_F", "HUMAN_PK_CLF_ORAL", "HUMAN_PK_VDF_ORAL", "KA",
    "ORAL_AUC", "ORAL_CMAX", "TMAX",
})

PREDICT_ALL_EXECUTION_ENDPOINTS = (
    PUBLISHABLE_CURRENT_ENDPOINTS | MECHANISTIC_EXECUTION_ENDPOINTS
)

assert len(PUBLISHABLE_CURRENT_ENDPOINTS) == 32
assert len(PREDICT_ALL_EXECUTION_ENDPOINTS) == 36
assert len(
    PUBLISHABLE_CURRENT_ENDPOINTS
    | MECHANISTIC_EXECUTION_ENDPOINTS
    | MODEL_NOT_REGISTERED_ENDPOINTS
    | MODEL_UNAVAILABLE_ENDPOINTS
    | CURRENT_DATA_CEILING_ENDPOINTS
    | CONTEXT_REQUIRED_ENDPOINTS
) == 59
