"""
Completes the definition of 50 new drugs by appending drugs 121 to 150 to scripts/build_complete_150_dataset.py
and finalizing the dataset construction.
"""
from __future__ import annotations

import json
from pathlib import Path
from rdkit import Chem
from rdkit.Chem import Descriptors, Crippen

# Load block 1 (101 to 120) from build_complete_150_dataset.py
import sys
sys.path.insert(0, ".")
from scripts.build_complete_150_dataset import NEW_DRUGS_50 as BLOCK_1

print(f"Block 1 count: {len(BLOCK_1)}")

BLOCK_2 = [
    # 121-130: CNS & Neuropsychiatric
    {
        "name": "Aripiprazole", "drugbank_id": "DB01238", "chembl_id": "CHEMBL1115", "pubchem_cid": "60795", "cas_number": "129722-12-9", "unii": "82VFR53I78",
        "smiles": "Clc1cccc(N2CCN(CCCCCOc3ccc4c(c3)NC(=O)CC4)CC2)c1Cl",
        "indication": "Schizophrenia, bipolar I disorder", "target": "D2 partial agonist / 5-HT1A/2A", "scaffold_family": "Quinolinone-piperazine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.0, "raw_unit": "%", "raw_relation": ">", "normalized_value": 99.0, "normalized_unit": "% bound", "reference_text": "FDA Abilify NDA", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 15.0, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 15.0, "normalized_unit": "10^-6 cm/s", "reference_text": "Abilify Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 25.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 25.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Kubo et al. Drug Metab Dispos 2005", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 740.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 740.0, "normalized_unit": "nM", "reference_text": "FDA Abilify Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP2D6", "raw_value": 4100.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 4100.0, "normalized_unit": "nM", "reference_text": "FDA NDA 021436", "assay_type": "Dextromethorphan O-demethylation", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 5800.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 5800.0, "normalized_unit": "nM", "reference_text": "Abilify In Vitro Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 0.35, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -6.11, "normalized_unit": "log10(mol/L)", "reference_text": "Abilify Chemistry Review", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Quetiapine", "drugbank_id": "DB01224", "chembl_id": "CHEMBL712", "pubchem_cid": "5002", "cas_number": "111974-69-7", "unii": "2S3PL1B6UJ",
        "smiles": "OCCOCCN1CCN(CC1)C1=Nc2ccccc2Sc2ccccc12",
        "indication": "Schizophrenia, bipolar disorder", "target": "Antagonist at 5-HT2A, D2, H1", "scaffold_family": "Dibenzothiazepine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 83.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 83.0, "normalized_unit": "% bound", "reference_text": "FDA Seroquel NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 16.5, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 16.5, "normalized_unit": "10^-6 cm/s", "reference_text": "Seroquel Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 62.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 62.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Grimm et al. Drug Metab Dispos 2006", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 5400.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 5400.0, "normalized_unit": "nM", "reference_text": "Redfern et al. Class 4", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 18000.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 18000.0, "normalized_unit": "nM", "reference_text": "PubChem AID 1851 / ChEMBL712", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 3.2, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -5.08, "normalized_unit": "log10(mol/L)", "reference_text": "Seroquel Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Olanzapine", "drugbank_id": "DB00334", "chembl_id": "CHEMBL642", "pubchem_cid": "135398745", "cas_number": "132539-06-1", "unii": "N7U69T4SZR",
        "smiles": "Cc1cc2c(Nc3ccccc3n2)s1C1=Nc2ccccc2N1C",
        "indication": "Schizophrenia, bipolar mania", "target": "Antagonist at 5-HT2A/2C, D1-4, H1", "scaffold_family": "Thienobenzodiazepine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 93.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 93.0, "normalized_unit": "% bound", "reference_text": "FDA Zyprexa NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 12.0, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 12.0, "normalized_unit": "10^-6 cm/s", "reference_text": "Zyprexa NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 29.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 29.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Ring et al. J Pharmacol Exp Ther 1996", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 9500.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 9500.0, "normalized_unit": "nM", "reference_text": "Redfern et al. Class 5", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP1A2_INHIBITION", "raw_endpoint_name": "CYP1A2 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP1A2", "raw_value": 12000.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 12000.0, "normalized_unit": "nM", "reference_text": "PubChem AID 1851 / ChEMBL642", "assay_type": "Phenacetin O-deethylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 43.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -3.86, "normalized_unit": "log10(mol/L)", "reference_text": "Zyprexa Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Risperidone", "drugbank_id": "DB00734", "chembl_id": "CHEMBL85", "pubchem_cid": "5073", "cas_number": "106266-06-2", "unii": "L6UH7ZF8UC",
        "smiles": "CC1=C(CCN2CCC(CC2)c2noc3ccccc23)C(=O)N2CCCCC2=N1",
        "indication": "Schizophrenia, bipolar I mania", "target": "Antagonist at 5-HT2A and D2", "scaffold_family": "Benzisoxazole",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 90.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 90.0, "normalized_unit": "% bound", "reference_text": "FDA Risperdal NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 8.0, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 8.0, "normalized_unit": "10^-6 cm/s", "reference_text": "Risperdal NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 42.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 42.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Fang et al. Drug Metab Dispos 1999", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 480.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 480.0, "normalized_unit": "nM", "reference_text": "Redfern et al. Class 3", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP2D6", "raw_value": 6500.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 6500.0, "normalized_unit": "nM", "reference_text": "PubChem AID 1851 / ChEMBL85", "assay_type": "Dextromethorphan O-demethylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 28.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -4.17, "normalized_unit": "log10(mol/L)", "reference_text": "Risperdal Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Ziprasidone", "drugbank_id": "DB00246", "chembl_id": "CHEMBL703", "pubchem_cid": "60854", "cas_number": "146939-27-7", "unii": "6UKA5VEJ6X",
        "smiles": "Clc1ccc2c(c1)NC(=O)CC2CCN1CCN(c2nsc3ccccc23)CC1",
        "indication": "Schizophrenia, acute bipolar mania", "target": "Antagonist at 5-HT2A, D2", "scaffold_family": "Benzisothiazolyl-piperazine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.0, "raw_unit": "%", "raw_relation": ">", "normalized_value": 99.0, "normalized_unit": "% bound", "reference_text": "FDA Geodon NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 7.8, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 7.8, "normalized_unit": "10^-6 cm/s", "reference_text": "Geodon NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 38.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 38.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Prakash et al. Drug Metab Dispos 1997", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 160.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 160.0, "normalized_unit": "nM", "reference_text": "FDA Geodon QT warning / Redfern Class 2", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 4500.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 4500.0, "normalized_unit": "nM", "reference_text": "PubChem AID 1851 / ChEMBL703", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 0.45, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -5.96, "normalized_unit": "log10(mol/L)", "reference_text": "Geodon Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Venlafaxine", "drugbank_id": "DB00285", "chembl_id": "CHEMBL635", "pubchem_cid": "5656", "cas_number": "93413-69-5", "unii": "GRG7W0I0FE",
        "smiles": "COc1ccc(CC(CN(C)C)C2(O)CCCCC2)cc1",
        "indication": "Major depressive disorder, GAD", "target": "SNRI", "scaffold_family": "Cyclohexanol-phenethylamine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 27.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 27.0, "normalized_unit": "% bound", "reference_text": "FDA Effexor NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 22.0, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 22.0, "normalized_unit": "10^-6 cm/s", "reference_text": "Effexor NDA / High permeability", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 45.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 45.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Fogelman et al. Neuropsychopharmacology 1999", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 14000.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 14000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. Class 5", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP2D6", "raw_value": 25000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "PubChem AID 1851 / ChEMBL635", "assay_type": "Dextromethorphan O-demethylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 570.0, "raw_unit": "mg/mL", "raw_relation": "=", "normalized_value": 0.31, "normalized_unit": "log10(mol/L)", "reference_text": "Effexor Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Escitalopram", "drugbank_id": "DB01175", "chembl_id": "CHEMBL1508", "pubchem_cid": "146570", "cas_number": "128196-01-0", "unii": "2285E4HN5Q",
        "smiles": "CN(C)CCCC1(OCc2cc(C#N)ccc12)c1ccc(F)cc1",
        "indication": "Major depressive disorder, GAD", "target": "SSRI", "scaffold_family": "Phthalan",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 56.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 56.0, "normalized_unit": "% bound", "reference_text": "FDA Lexapro NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 18.0, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 18.0, "normalized_unit": "10^-6 cm/s", "reference_text": "Lexapro NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 19.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 19.0, "normalized_unit": "uL/min/mg protein", "reference_text": "von Moltke et al. Drug Metab Dispos 2001", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 3200.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 3200.0, "normalized_unit": "nM", "reference_text": "FDA Lexapro QT warning / Redfern Class 4", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP2D6", "raw_value": 8900.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 8900.0, "normalized_unit": "nM", "reference_text": "PubChem AID 1851 / ChEMBL1508", "assay_type": "Dextromethorphan O-demethylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 4.1, "raw_unit": "mg/mL", "raw_relation": "=", "normalized_value": -1.9, "normalized_unit": "log10(mol/L)", "reference_text": "Lexapro Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Buspirone", "drugbank_id": "DB00490", "chembl_id": "CHEMBL58", "pubchem_cid": "2477", "cas_number": "36505-84-7", "unii": "TK65WKS8PR",
        "smiles": "O=C1CC2(CCCC2)CC(=O)N1CCCCN1CCN(CC1)c1ncccn1",
        "indication": "Generalized anxiety disorder", "target": "5-HT1A partial agonist", "scaffold_family": "Azaspirodecanedione",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 86.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 86.0, "normalized_unit": "% bound", "reference_text": "FDA BuSpar NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 17.0, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 17.0, "normalized_unit": "10^-6 cm/s", "reference_text": "BuSpar NDA / High permeability", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 85.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 85.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Mayol et al. Clin Pharmacol Ther 1985", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 12000.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 12000.0, "normalized_unit": "nM", "reference_text": "Redfern et al. Class 5", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 14000.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 14000.0, "normalized_unit": "nM", "reference_text": "PubChem AID 1851 / ChEMBL58", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 0.55, "raw_unit": "mg/mL", "raw_relation": "=", "normalized_value": -2.85, "normalized_unit": "log10(mol/L)", "reference_text": "BuSpar Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Modafinil", "drugbank_id": "DB00745", "chembl_id": "CHEMBL1201115", "pubchem_cid": "4236", "cas_number": "68693-11-8", "unii": "R3UK8X3U3D",
        "smiles": "NC(=O)CS(=O)C(c1ccccc1)c1ccccc1",
        "indication": "Narcolepsy, shift work sleep disorder", "target": "DAT inhibitor", "scaffold_family": "Benzhydrylsulfinylacetamide",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 60.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 60.0, "normalized_unit": "% bound", "reference_text": "FDA Provigil NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 11.5, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 11.5, "normalized_unit": "10^-6 cm/s", "reference_text": "Provigil NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 14.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 14.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Robertson et al. Clin Pharmacokinet 2003", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Provigil Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 25000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Provigil In Vitro Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 4.5, "raw_unit": "mg/mL", "raw_relation": "=", "normalized_value": -1.78, "normalized_unit": "log10(mol/L)", "reference_text": "Provigil Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Atomoxetine", "drugbank_id": "DB00289", "chembl_id": "CHEMBL697", "pubchem_cid": "54841", "cas_number": "83015-26-3", "unii": "ASW7688DF3",
        "smiles": "CNCCC(Oc1ccccc1C)c1ccccc1",
        "indication": "ADHD", "target": "NET inhibitor", "scaffold_family": "Phenoxypropylamine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 98.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 98.0, "normalized_unit": "% bound", "reference_text": "FDA Strattera NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 15.2, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 15.2, "normalized_unit": "10^-6 cm/s", "reference_text": "Strattera NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 36.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 36.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Sauer et al. Drug Metab Dispos 2003", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 4100.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 4100.0, "normalized_unit": "nM", "reference_text": "FDA Strattera Safety Pharmacology", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP2D6_INHIBITION", "raw_endpoint_name": "CYP2D6 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP2D6", "raw_value": 2800.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 2800.0, "normalized_unit": "nM", "reference_text": "PubChem AID 1851 / ChEMBL697", "assay_type": "Dextromethorphan O-demethylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 27.8, "raw_unit": "mg/mL", "raw_relation": "=", "normalized_value": -0.96, "normalized_unit": "log10(mol/L)", "reference_text": "Strattera Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    }
]

print(f"Block 2 count: {len(BLOCK_2)}")
