"""
Curates blocks 3 (131-140 Antivirals) and 4 (141-150 Immunology/Metabolic).
"""
from __future__ import annotations

BLOCK_3 = [
    # 131-140: Infectious Disease & Antivirals
    {
        "name": "Sofosbuvir", "drugbank_id": "DB08934", "chembl_id": "CHEMBL1259059", "pubchem_cid": "45375808", "cas_number": "1190307-88-0", "unii": "WJ6CA3ZU8B",
        "smiles": "CC(C)OC(=O)C(C)NP(=O)(OCC1OC(n2ccc(=O)[nH]c2=O)C(F)(C)C1O)Oc1ccccc1",
        "indication": "Chronic hepatitis C", "target": "HCV NS5B polymerase", "scaffold_family": "Nucleotide prodrug",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 63.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 63.0, "normalized_unit": "% bound", "reference_text": "FDA Sovaldi NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 5.5, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 5.5, "normalized_unit": "10^-6 cm/s", "reference_text": "Sovaldi NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 12.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 12.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Kirby et al. AAC 2013", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Sovaldi Safety Pharmacology", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA NDA 204671", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 1.2, "raw_unit": "mg/mL", "raw_relation": "=", "normalized_value": -2.64, "normalized_unit": "log10(mol/L)", "reference_text": "Sovaldi Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Ledipasvir", "drugbank_id": "DB09027", "chembl_id": "CHEMBL2029511", "pubchem_cid": "67505836", "cas_number": "1256388-51-8", "unii": "100911OU36",
        "smiles": "COC(=O)NC(C(=O)N1CCC(CC1)c1nc2ccc(-c3ccc4c(c3)C3(CCCC3)c3cc(-c5ccc6nc([nH]c6c5)C5CCCN5C(=O)C(NC(=O)OC)C(C)C)ccc3-4)cc2[nH]1)C(C)C",
        "indication": "Chronic hepatitis C genotype 1", "target": "HCV NS5A inhibitor", "scaffold_family": "Benzimidazole-pyrrolidine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.8, "raw_unit": "%", "raw_relation": ">", "normalized_value": 99.8, "normalized_unit": "% bound", "reference_text": "FDA Harvoni NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 0.35, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 0.35, "normalized_unit": "10^-6 cm/s", "reference_text": "Harvoni NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 5.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 5.0, "normalized_unit": "uL/min/mg protein", "reference_text": "German et al. Clin Pharmacokinet 2016", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Harvoni Safety Pharmacology", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 25000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "FDA NDA 205834", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 0.1, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -6.95, "normalized_unit": "log10(mol/L)", "reference_text": "Harvoni Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Daclatasvir", "drugbank_id": "DB09102", "chembl_id": "CHEMBL2095204", "pubchem_cid": "25151504", "cas_number": "1009119-64-5", "unii": "T9A9922097",
        "smiles": "COC(=O)NC(C(=O)N1CCCC1c1nc(-c2ccc(-c3ccc(-c4c[nH]c(C5CCCN5C(=O)C(NC(=O)OC)C(C)C)n4)cc3)cc2)c[nH]1)C(C)C",
        "indication": "Chronic hepatitis C", "target": "HCV NS5A inhibitor", "scaffold_family": "Biphenyl-diimidazole",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 99.0, "normalized_unit": "% bound", "reference_text": "FDA Daklinza NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 1.2, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 1.2, "normalized_unit": "10^-6 cm/s", "reference_text": "Daklinza NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 16.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 16.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Bifano et al. Clin Pharmacokinet 2013", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 24000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 24000.0, "normalized_unit": "nM", "reference_text": "FDA Daklinza Safety Pharmacology", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 12000.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 12000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Daklinza In Vitro CYP Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 2.5, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -5.47, "normalized_unit": "log10(mol/L)", "reference_text": "Daklinza Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Dolutegravir", "drugbank_id": "DB08930", "chembl_id": "CHEMBL1259160", "pubchem_cid": "54726191", "cas_number": "1051375-16-6", "unii": "G1W50L0NS2",
        "smiles": "CC1CCOc2c1n1cc(C(=O)NCc3ccc(F)cc3F)c(=O)c(O)c1c(=O)n2C",
        "indication": "HIV-1 infection", "target": "HIV-1 integrase strand transfer inhibitor", "scaffold_family": "Polycyclic pyridinone",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.3, "raw_unit": "%", "raw_relation": ">", "normalized_value": 99.3, "normalized_unit": "% bound", "reference_text": "FDA Tivicay NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 3.8, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 3.8, "normalized_unit": "10^-6 cm/s", "reference_text": "Tivicay NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 11.5, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 11.5, "normalized_unit": "uL/min/mg protein", "reference_text": "Cottrell et al. J Clin Pharmacol 2013", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Tivicay Safety Pharmacology", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Tivicay In Vitro CYP Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 18.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -4.37, "normalized_unit": "log10(mol/L)", "reference_text": "Tivicay Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Raltegravir", "drugbank_id": "DB06817", "chembl_id": "CHEMBL410885", "pubchem_cid": "54671008", "cas_number": "518048-05-0", "unii": "4RQL65809V",
        "smiles": "Cc1nc(C(=O)NCc2ccc(F)cc2)c(O)c(=O)n1Cc1nc(C)(C)c(=O)[nH]1",
        "indication": "HIV-1 infection", "target": "HIV-1 integrase inhibitor", "scaffold_family": "Hydroxypyrimidinone",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 83.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 83.0, "normalized_unit": "% bound", "reference_text": "FDA Isentress NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 2.5, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 2.5, "normalized_unit": "10^-6 cm/s", "reference_text": "Isentress NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 8.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 8.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Kassahun et al. Drug Metab Dispos 2007", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Isentress Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Isentress", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 75.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -3.77, "normalized_unit": "log10(mol/L)", "reference_text": "Isentress Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Maraviroc", "drugbank_id": "DB00888", "chembl_id": "CHEMBL1201127", "pubchem_cid": "3002977", "cas_number": "376348-65-1", "unii": "201384S138",
        "smiles": "CC(C)C(=O)N1CC2CCC1CC(NC(=O)C1(CC1)c1ccc(F)cc1F)N2CCC(c1ccccc1)N1CCC(F)(F)CC1",
        "indication": "CCR5-tropic HIV-1 infection", "target": "CCR5 receptor antagonist", "scaffold_family": "Tropane",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 76.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 76.0, "normalized_unit": "% bound", "reference_text": "FDA Selzentry NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 4.5, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 4.5, "normalized_unit": "10^-6 cm/s", "reference_text": "Selzentry NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 48.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 48.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Walker et al. Drug Metab Dispos 2005", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 11000.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 11000.0, "normalized_unit": "nM", "reference_text": "FDA Selzentry Safety Pharmacology", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 22000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 22000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Selzentry In Vitro Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 11.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -4.67, "normalized_unit": "log10(mol/L)", "reference_text": "Selzentry Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Tenofovir alafenamide", "drugbank_id": "DB09299", "chembl_id": "CHEMBL2105757", "pubchem_cid": "60164625", "cas_number": "379270-37-8", "unii": "EL2IC3UQ53",
        "smiles": "CC(C)OC(=O)C(C)NP(=O)(OCC(C)n1cnc2c(N)ncnc12)Oc3ccccc3",
        "indication": "HIV-1 infection, chronic hepatitis B", "target": "Reverse transcriptase prodrug", "scaffold_family": "Adenine phosphonamidate",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 80.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 80.0, "normalized_unit": "% bound", "reference_text": "FDA Vemlidy NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 3.2, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 3.2, "normalized_unit": "10^-6 cm/s", "reference_text": "Vemlidy NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 18.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 18.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Birkus et al. AAC 2007", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Vemlidy Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Vemlidy", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 4.8, "raw_unit": "mg/mL", "raw_relation": "=", "normalized_value": -2.0, "normalized_unit": "log10(mol/L)", "reference_text": "Vemlidy Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Rilpivirine", "drugbank_id": "DB08864", "chembl_id": "CHEMBL444158", "pubchem_cid": "6451164", "cas_number": "500287-72-9", "unii": "F2291U631Q",
        "smiles": "Cc1cc(C#N)cc(C)c1Nc1nc(Nc2ccc(C#N)cc2)nc(C=CC#N)n1",
        "indication": "HIV-1 infection", "target": "NNRTI", "scaffold_family": "Diarylpyrimidine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.7, "raw_unit": "%", "raw_relation": ">", "normalized_value": 99.7, "normalized_unit": "% bound", "reference_text": "FDA Edurant NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 6.8, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 6.8, "normalized_unit": "10^-6 cm/s", "reference_text": "Edurant NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 22.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 22.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Stevens et al. AAC 2011", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 500.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 500.0, "normalized_unit": "nM", "reference_text": "FDA Edurant Safety Pharmacology hERG IC50 0.5 uM", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 4100.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 4100.0, "normalized_unit": "nM", "reference_text": "FDA NDA Edurant", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 0.02, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -7.26, "normalized_unit": "log10(mol/L)", "reference_text": "Edurant Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Baloxavir marboxil", "drugbank_id": "DB13997", "chembl_id": "CHEMBL4297672", "pubchem_cid": "124081896", "cas_number": "1985606-14-1", "unii": "2S6T8A869K",
        "smiles": "COC(=O)OCOC1=C2C(=O)N3CCOCC3N(N2C=CC1=O)C4C5=C(CSC6=CC=CC=C46)C(=C(C=C5)F)F",
        "indication": "Influenza A and B", "target": "Cap-dependent endonuclease prodrug", "scaffold_family": "Pyridopyridazine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 93.5, "raw_unit": "%", "raw_relation": "=", "normalized_value": 93.5, "normalized_unit": "% bound", "reference_text": "FDA Xofluza NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 6.1, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 6.1, "normalized_unit": "10^-6 cm/s", "reference_text": "Xofluza NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 15.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 15.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Koshimichi et al. Clin Pharmacokinet 2019", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Xofluza Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 18000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 18000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Xofluza", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 1.1, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -5.73, "normalized_unit": "log10(mol/L)", "reference_text": "Xofluza Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Remdesivir", "drugbank_id": "DB14761", "chembl_id": "CHEMBL3991512", "pubchem_cid": "121304016", "cas_number": "1809249-37-3", "unii": "3QKI37EEHE",
        "smiles": "CCC(CC)COC(=O)C(C)NP(=O)(OCC1OC(C#N)(c2ccc3n2ncnc3N)C(O)C1O)Oc4ccccc4",
        "indication": "COVID-19", "target": "RNA-dependent RNA polymerase prodrug", "scaffold_family": "Pyrrolotriazine phosphoramidate",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 88.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 88.0, "normalized_unit": "% bound", "reference_text": "FDA Veklury NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 2.1, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 2.1, "normalized_unit": "10^-6 cm/s", "reference_text": "Veklury NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 58.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 58.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Yang et al. AAC 2020", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 28000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 28000.0, "normalized_unit": "nM", "reference_text": "FDA Veklury Safety Pharmacology", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 9500.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 9500.0, "normalized_unit": "nM", "reference_text": "FDA NDA Veklury In Vitro Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 12.5, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -4.68, "normalized_unit": "log10(mol/L)", "reference_text": "Veklury Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    }
]

BLOCK_4 = [
    # 141-150: Immunology & Metabolic
    {
        "name": "Tofacitinib", "drugbank_id": "DB08895", "chembl_id": "CHEMBL1173655", "pubchem_cid": "9926791", "cas_number": "477600-75-2", "unii": "4KLZ3U881P",
        "smiles": "CC1CCN(CC1N(C)c1ncnc2[nH]ccc12)C(=O)CC#N",
        "indication": "Rheumatoid arthritis", "target": "JAK1 / JAK3 inhibitor", "scaffold_family": "Pyrrolopyrimidine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 40.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 40.0, "normalized_unit": "% bound", "reference_text": "FDA Xeljanz NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 14.0, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 14.0, "normalized_unit": "10^-6 cm/s", "reference_text": "Xeljanz NDA / High permeability", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 32.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 32.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Dowty et al. Drug Metab Dispos 2014", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Xeljanz Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 25000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Xeljanz", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 2.9, "raw_unit": "mg/mL", "raw_relation": "=", "normalized_value": -2.03, "normalized_unit": "log10(mol/L)", "reference_text": "Xeljanz Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Baricitinib", "drugbank_id": "DB11815", "chembl_id": "CHEMBL2105759", "pubchem_cid": "44205240", "cas_number": "1187594-09-7", "unii": "F41NYQRF3R",
        "smiles": "CCS(=O)(=O)N1CC(C#N)(C1)n1cc(-c2ncnc3[nH]ccc23)cn1",
        "indication": "Rheumatoid arthritis, alopecia areata", "target": "JAK1 / JAK2 inhibitor", "scaffold_family": "Azetidine-pyrazolopyrimidine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 50.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 50.0, "normalized_unit": "% bound", "reference_text": "FDA Olumiant NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 7.2, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 7.2, "normalized_unit": "10^-6 cm/s", "reference_text": "Olumiant NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 11.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 11.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Posada et al. Clin Pharmacokinet 2017", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Olumiant Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Olumiant", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 350.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -3.03, "normalized_unit": "log10(mol/L)", "reference_text": "Olumiant Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Upadacitinib", "drugbank_id": "DB12035", "chembl_id": "CHEMBL3707348", "pubchem_cid": "77843336", "cas_number": "1310726-60-3", "unii": "4RA0KN46E0",
        "smiles": "CC(C#N)C1CN(C1)c1ncnc2[nH]ccc12",
        "indication": "Rheumatoid arthritis, atopic dermatitis", "target": "Selective JAK1 inhibitor", "scaffold_family": "Pyrrolopyrimidine-azetidine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 52.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 52.0, "normalized_unit": "% bound", "reference_text": "FDA Rinvoq NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 9.5, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 9.5, "normalized_unit": "10^-6 cm/s", "reference_text": "Rinvoq NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 24.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 24.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Mohamed et al. Clin Pharmacokinet 2019", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Rinvoq Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 25000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Rinvoq", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 38.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -4.01, "normalized_unit": "log10(mol/L)", "reference_text": "Rinvoq Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Ruxolitinib", "drugbank_id": "DB08877", "chembl_id": "CHEMBL1762649", "pubchem_cid": "25126798", "cas_number": "941678-49-5", "unii": "82V8850O5H",
        "smiles": "N#CC(C1CCCC1)n1cc(-c2ncnc3[nH]ccc23)cn1",
        "indication": "Myelofibrosis, polycythemia vera", "target": "JAK1 / JAK2 inhibitor", "scaffold_family": "Cyclopentylpropanenitrile pyrrolopyrimidine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 97.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 97.0, "normalized_unit": "% bound", "reference_text": "FDA Jakafi NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 11.0, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 11.0, "normalized_unit": "10^-6 cm/s", "reference_text": "Jakafi NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 42.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 42.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Shi et al. J Clin Pharmacol 2011", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 25000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "FDA Jakafi Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 14000.0, "raw_unit": "nM", "raw_relation": "=", "normalized_value": 14000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Jakafi In Vitro Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 110.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -3.45, "normalized_unit": "log10(mol/L)", "reference_text": "Jakafi Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Apremilast", "drugbank_id": "DB09065", "chembl_id": "CHEMBL2095205", "pubchem_cid": "11561674", "cas_number": "608141-41-9", "unii": "47G62L717S",
        "smiles": "CCOc1ccc(C(C)N2C(=O)c3ccc(NC(=O)C)cc3C2=O)cc1OC",
        "indication": "Psoriatic arthritis, plaque psoriasis", "target": "PDE4 inhibitor", "scaffold_family": "Phthalimide",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 68.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 68.0, "normalized_unit": "% bound", "reference_text": "FDA Otezla NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 12.5, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 12.5, "normalized_unit": "10^-6 cm/s", "reference_text": "Otezla NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 26.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 26.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Hoffmann et al. Drug Metab Dispos 2011", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Otezla Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 28000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 28000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Otezla", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 8.5, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -4.73, "normalized_unit": "log10(mol/L)", "reference_text": "Otezla Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Empagliflozin", "drugbank_id": "DB09038", "chembl_id": "CHEMBL2107830", "pubchem_cid": "11949646", "cas_number": "864070-44-0", "unii": "HDC1R2J35U",
        "smiles": "OCC1OC(Cc2ccc(Cl)c(Cc3ccc4c(c3)CCCO4)c2)C(O)C(O)C1O",
        "indication": "Type 2 diabetes, heart failure", "target": "SGLT2 inhibitor", "scaffold_family": "C-glucoside",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 86.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 86.0, "normalized_unit": "% bound", "reference_text": "FDA Jardiance NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 4.5, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 4.5, "normalized_unit": "10^-6 cm/s", "reference_text": "Jardiance NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 8.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 8.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Macha et al. Clin Pharmacokinet 2014", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Jardiance Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Jardiance In Vitro Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 340.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -3.12, "normalized_unit": "log10(mol/L)", "reference_text": "Jardiance Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Dapagliflozin", "drugbank_id": "DB06292", "chembl_id": "CHEMBL509176", "pubchem_cid": "9887712", "cas_number": "461432-26-8", "unii": "1ULL0QJ8UC",
        "smiles": "CCOc1ccc(Cc2cc(C3OC(CO)C(O)C(O)C3O)ccc2Cl)cc1",
        "indication": "Type 2 diabetes, CKD", "target": "SGLT2 inhibitor", "scaffold_family": "C-aryl glucoside",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 91.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 91.0, "normalized_unit": "% bound", "reference_text": "FDA Farxiga NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 5.2, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 5.2, "normalized_unit": "10^-6 cm/s", "reference_text": "Farxiga NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 11.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 11.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Kasichayanula et al. Clin Pharmacokinet 2014", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Farxiga Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Farxiga In Vitro Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 210.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -3.29, "normalized_unit": "log10(mol/L)", "reference_text": "Farxiga Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Canagliflozin", "drugbank_id": "DB08907", "chembl_id": "CHEMBL1762648", "pubchem_cid": "24812758", "cas_number": "842133-18-0", "unii": "0944PBR1VQ",
        "smiles": "Cc1ccc(Cc2cc(C3OC(CO)C(O)C(O)C3O)ccc2-c2ccc(F)s2)cc1",
        "indication": "Type 2 diabetes", "target": "SGLT2 inhibitor", "scaffold_family": "C-aryl glucoside / Thiophene",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 99.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 99.0, "normalized_unit": "% bound", "reference_text": "FDA Invokana NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 7.4, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 7.4, "normalized_unit": "10^-6 cm/s", "reference_text": "Invokana NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 14.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 14.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Devineni et al. Clin Pharmacokinet 2013", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Invokana Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 24000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 24000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Invokana In Vitro Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 85.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -3.72, "normalized_unit": "log10(mol/L)", "reference_text": "Invokana Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Linagliptin", "drugbank_id": "DB08882", "chembl_id": "CHEMBL1201833", "pubchem_cid": "10096344", "cas_number": "668270-12-0", "unii": "3X29UMB2TZ",
        "smiles": "CC#CCn1c(=O)c2c(ncn2Cc2nc3ccccc3c(=O)n2C)n(C)c1=O",
        "indication": "Type 2 diabetes", "target": "DPP-4 inhibitor", "scaffold_family": "Xanthine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 75.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 75.0, "normalized_unit": "% bound", "reference_text": "FDA Tradjenta NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 1.1, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 1.1, "normalized_unit": "10^-6 cm/s", "reference_text": "Tradjenta NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 6.5, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 6.5, "normalized_unit": "uL/min/mg protein", "reference_text": "Blech et al. Drug Metab Dispos 2010", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Tradjenta Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 25000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 25000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Tradjenta", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 90.0, "raw_unit": "ug/mL", "raw_relation": "=", "normalized_value": -3.72, "normalized_unit": "log10(mol/L)", "reference_text": "Tradjenta Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    },
    {
        "name": "Saxagliptin", "drugbank_id": "DB06335", "chembl_id": "CHEMBL385517", "pubchem_cid": "11243969", "cas_number": "361442-04-8", "unii": "54H68KLT5I",
        "smiles": "NC(C(=O)N1CC2CC1C2(C#N)O)C13CC2CC(CC(O)(C2)C1)C3",
        "indication": "Type 2 diabetes", "target": "DPP-4 inhibitor", "scaffold_family": "Adamantylglycine",
        "observations": [
            {"canonical_endpoint_id": "HUMAN_PPB", "raw_endpoint_name": "Human Plasma Protein Binding", "section": "ADMET", "species": "Homo sapiens", "matrix": "Human Plasma", "raw_value": 10.0, "raw_unit": "%", "raw_relation": "=", "normalized_value": 10.0, "normalized_unit": "% bound", "reference_text": "FDA Onglyza NDA ClinPharm", "assay_type": "Equilibrium Dialysis", "training_eligible": True},
            {"canonical_endpoint_id": "CACO2_PAPP_AB", "raw_endpoint_name": "Caco-2 Permeability (A to B)", "section": "ADMET", "species": "Homo sapiens", "matrix": "Caco-2 Monolayer", "raw_value": 2.4, "raw_unit": "10^-6 cm/s", "raw_relation": "=", "normalized_value": 2.4, "normalized_unit": "10^-6 cm/s", "reference_text": "Onglyza NDA Biopharmaceutics", "assay_type": "Transwell Monolayer Flux", "training_eligible": True},
            {"canonical_endpoint_id": "HLM_CLINT", "raw_endpoint_name": "Human Liver Microsomes Clint", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Pooled Human Liver Microsomes", "raw_value": 28.0, "raw_unit": "uL/min/mg", "raw_relation": "=", "normalized_value": 28.0, "normalized_unit": "uL/min/mg protein", "reference_text": "Fura et al. Drug Metab Dispos 2009", "assay_type": "Substrate Depletion Assay", "training_eligible": True},
            {"canonical_endpoint_id": "HERG_LIABILITY", "raw_endpoint_name": "hERG Potassium Channel Inhibition", "section": "SAFETY", "species": "Homo sapiens", "matrix": "HEK293 hERG Patch-Clamp", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA Onglyza Safety Review", "assay_type": "Manual Patch Clamp", "training_eligible": True},
            {"canonical_endpoint_id": "CYP3A4_INHIBITION", "raw_endpoint_name": "CYP3A4 Direct Reversible Inhibition", "section": "METABOLISM", "species": "Homo sapiens", "matrix": "Recombinant Human CYP3A4", "raw_value": 30000.0, "raw_unit": "nM", "raw_relation": ">", "normalized_value": 30000.0, "normalized_unit": "nM", "reference_text": "FDA NDA Onglyza In Vitro Studies", "assay_type": "Midazolam 1'-hydroxylation", "training_eligible": True},
            {"canonical_endpoint_id": "SOLUBILITY_THERMODYNAMIC", "raw_endpoint_name": "Thermodynamic Aqueous Solubility", "section": "PHYSICOCHEMICAL", "species": "None", "matrix": "Phosphate Buffer pH 7.0", "raw_value": 17.5, "raw_unit": "mg/mL", "raw_relation": "=", "normalized_value": -1.25, "normalized_unit": "log10(mol/L)", "reference_text": "Onglyza Physical Chemistry", "assay_type": "Shake-Flask HPLC", "training_eligible": True}
        ]
    }
]

print(f"Block 3 count: {len(BLOCK_3)}, Block 4 count: {len(BLOCK_4)}")
