#!/usr/bin/env python3
"""Generate the Stage 4D-4 master matrix and its human-readable policy table."""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.endpoint_contracts import ENDPOINT_CONTRACTS  # noqa: E402
from backend.endpoint_strategy_registry import (
    ENDPOINT_STRATEGY_REGISTRY,
    RUNTIME_ADMET_MODEL_ENDPOINTS,
    get_registry_summary,
)


MATRIX_PATH = ROOT / "validation" / "stage4d4_endpoint_strategy_matrix.json"
DOC_PATH = ROOT / "docs" / "stage4d4-endpoint-strategy.md"


def _cell(value: object) -> str:
    if value is None or value == []:
        return "—"
    if isinstance(value, list):
        value = ", ".join(str(item) for item in value)
    return str(value).replace("|", "\\|").replace("\n", " ")


def build_matrix() -> dict:
    summary = get_registry_summary()
    policies = summary["endpoints"]
    final_review = {}
    for name, policy in policies.items():
        calibration_validated = policy["calibration_status"] in {
            "CALIBRATION_VALIDATED", "CALIBRATION_PRODUCTION"
        }
        final_review[name] = {
            "production_primary": {
                "strategy": policy["primary_strategy"],
                "model_ids": policy["primary_model_ids"],
                "model_versions": policy["primary_model_versions"],
            },
            "shadow": {
                "strategy": policy["shadow_strategy"],
                "model_ids": policy["shadow_model_ids"],
                "model_versions": policy["shadow_model_versions"],
                "lifecycle_state": policy["shadow_promotion_status"],
            },
            "calibration_validated": calibration_validated,
            "calibration_status": policy["calibration_status"],
            "calibration_production_enabled": policy["calibration_production_enabled"],
            "adaptive_allowed_in_production": False,
            "adaptive_status": policy["adaptive_status"],
            "consensus_allowed_in_production": policy["consensus_status"] == "ALLOWED_PRODUCTION",
            "consensus_status": policy["consensus_status"],
            "limitations": policy["limitations"],
            "promotion_requirements": policy["promotion_requirements"],
            "rollback_policy": policy["rollback_policy"],
        }

    all_names = set(ENDPOINT_STRATEGY_REGISTRY)
    covered_inventory = set(ENDPOINT_CONTRACTS) | set(RUNTIME_ADMET_MODEL_ENDPOINTS)
    return {
        "artifact": "STAGE4D4_ENDPOINT_STRATEGY_MASTER_MATRIX",
        "registry_version": summary["registry_version"],
        "policy_date": summary["policy_date"],
        "production_behavior_changed": False,
        "ui_design_changed": False,
        "coverage": {
            "endpoint_contract_count": len(ENDPOINT_CONTRACTS),
            "runtime_admet_model_registry_count": len(RUNTIME_ADMET_MODEL_ENDPOINTS),
            "total_strategy_policy_count": len(ENDPOINT_STRATEGY_REGISTRY),
            "endpoint_contracts": sorted(ENDPOINT_CONTRACTS),
            "runtime_admet_model_registry": sorted(RUNTIME_ADMET_MODEL_ENDPOINTS),
            "policy_only_derived_endpoints": sorted(all_names - covered_inventory),
            "missing_endpoint_contract_strategies": sorted(set(ENDPOINT_CONTRACTS) - all_names),
            "missing_runtime_registry_strategies": sorted(set(RUNTIME_ADMET_MODEL_ENDPOINTS) - all_names),
        },
        "validation_violations": summary["violations"],
        "endpoints": policies,
        "final_scientific_review": final_review,
    }


def build_markdown(matrix: dict) -> str:
    lines = [
        "# Stage 4D-4 Endpoint Strategy Registry",
        "",
        "> Generated by `scripts/generate_stage4d4_strategy_artifacts.py` from "
        "`backend/endpoint_strategy_registry.py`. Do not edit the matrix by hand.",
        "",
        "Stage 4D-4 freezes endpoint-specific scientific policy without changing any "
        "production-visible prediction. Shadow strategies remain non-production research paths.",
        "",
        "| Endpoint | Primary strategy | Primary model(s) | Calibration | Shadow strategy | Adaptive | Validation | Limitations |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for name, policy in sorted(matrix["endpoints"].items()):
        lines.append("| " + " | ".join([
            _cell(name),
            _cell(policy["primary_strategy"]),
            _cell(policy["primary_model_ids"]),
            _cell(policy["calibration_status"]),
            _cell(policy["shadow_strategy"]),
            _cell(policy["adaptive_status"]),
            _cell(policy["validation_status"]),
            _cell(policy["limitations"]),
        ]) + " |")

    lines.extend([
        "",
        "## Frozen scientific decisions",
        "",
        "- Solubility production remains M1 single-core; adaptive weighting is research shadow only.",
        "- Caco-2 production remains M1 single-core; static consensus has insufficient promotion evidence.",
        "- CYP3A4 production remains M1 single-core; the fixed global blend is research shadow and dynamic adaptation has no predictive value beyond it.",
        "- hERG production remains raw M1 single-core. Platt-calibrated M1 is a research candidate; the calibration-selected M1/M2 blend was 100/0 and M2 is not promoted.",
        "- Metabolic soft spots use rank-fusion semantics and never average raw SyGMa/SMARTCyp scores.",
        "- PK/NCA/IVIVE/allometry/simulation methods retain their mechanistic evidence hierarchy and never enter ML consensus.",
        "- pKa is a rule estimate and conditional logD7.4 is a derived estimate; neither is labeled as validated ML.",
        "- Every unavailable endpoint returns `MODEL_UNAVAILABLE`; values are never fabricated.",
        "",
        "## Coverage",
        "",
        f"- Endpoint contracts: {matrix['coverage']['endpoint_contract_count']} / {matrix['coverage']['endpoint_contract_count']}",
        f"- Runtime ADMET model-registry endpoints: {matrix['coverage']['runtime_admet_model_registry_count']} / {matrix['coverage']['runtime_admet_model_registry_count']}",
        f"- Total governed policies: {matrix['coverage']['total_strategy_policy_count']}",
        f"- Registry consistency violations: {len(matrix['validation_violations'])}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    matrix = build_matrix()
    MATRIX_PATH.write_text(json.dumps(matrix, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    DOC_PATH.write_text(build_markdown(matrix), encoding="utf-8")


if __name__ == "__main__":
    main()
